#+TITLE:Build an R GIS desktop 
#+AUTHOR: Ivan Hanigan
#+email: ivan.hanigan@anu.edu.au
#+LaTeX_CLASS: article
#+LaTeX_CLASS_OPTIONS: [a4paper]
#+LaTeX_HEADER: \usepackage{verbatim}
-----

* SSH 
http://www.havetheknowhow.com/Configure-the-server/Install-Putty.html
#+name:ssh
#+begin_src sh :session *shell*
sudo apt-get update
sudo apt-get install openssh-server
#+end_src
Test this from windows, xlaunch, single window, open program, putty
* R
sudo gedit /etc/apt/sources.list
# add the line
deb http://cran.csiro.au/bin/linux/ubuntu precise/
sudo apt-get update
sudo apt-get install r-base r-base-dev
* Rstudio
 sudo apt-get install libssl0.9.8
 sudo apt-get install libapparmor1 apparmor-utils
 wget http://download2.rstudio.org/rstudio-server-0.96.316-amd64.deb
 sudo dpkg -i rstudio-server-0.96.316-amd64.deb
* git
sudo apt-get install git-core
* emacs
sudo add-apt-repository ppa:cassou/emacs
sudo apt-get update
sudo apt-get install emacs24 emacs24-el

* tex-live
sudo apt-get install texlive-full
* starter kit and ess
** kjhealy starter kit
rm -r ~/.emacs.d
# Deletes the folder
rm .emacs
git clone git://github.com/kjhealy/emacs-starter-kit ~/.emacs.d
cd ~/.emacs.d/
git submodule init
git submodule update
# change refs to bibtex etc in .emacs.d/kjhealy.org file, rename as username.org
# start emacs, ignore errors, M-x byte-compile
# errors on ubuntu? and redhat but worked on centos?
# SOLVED?  
** chunk templates
add to init.el

(define-skeleton org-skeleton
  "Header info for a emacs-org file."
  "Title: "
  "#+TITLE:" str " \n"
  "#+AUTHOR: Ivan Hanigan\n"
  "#+email: ivan.hanigan@anu.edu.au\n"
  "#+LaTeX_CLASS: article\n"
  "#+LaTeX_CLASS_OPTIONS: [a4paper]\n"
  "#+LATEX: \tableofcontents\n"
  "-----"
 )
(global-set-key [C-S-f4] 'org-skeleton)

;; additions to C-c C-e t by http://orgmode.org/worg/org-tutorials/org-beamer/tutorial.html

(define-skeleton beamer-skeleton
  "Additional header info for a emacs-beamer file."
  "#+startup: beamer\n"
  "#+LaTeX_CLASS: beamer\n"
  "#+LaTeX_CLASS_OPTIONS: [bigger]\n"
  "#+latex_header: \\mode<beamer>{\\usetheme{Madrid}}\n"
  "#+latex_header: \\usepackage{verbatim}\n"
  "#+BEAMER_FRAME_LEVEL: 2\n"
  "#+COLUMNS: \%40ITEM \%10BEAMER_env(Env) \%9BEAMER_envargs(Env Args) \%4BEAMER_col(Col) \%10BEAMER_extra(Extra)\n"
  "#+latex_header: \\AtBeginSection[]{\\begin{frame}<beamer>\\frametitle{Topic}\\tableofcontents[currentsection]\\end{frame}}\n"
 )
(global-set-key [C-S-f3] 'beamer-skeleton)


(define-skeleton newnode-skeleton
  "Info for a newnode chunk."
  "Title: "
  "#+name:" str "\n"
  "#+begin_src R :session *R* :tangle transformations_overview.r :exports none :eval no\n"
  "\n"
"newnode(name='" str "', \n"
" inputs = '" str "', \n"
" outputs = NA \n"
" )\n"
  "#+end_src\n"
)
(global-set-key [?\C-x ?\C-/] 'newnode-skeleton)

(define-skeleton chunk-skeleton
  "Info for a code chunk."
  "Title: "
  "#+name:" str "\n"
  "#+begin_src R :session *R* :tangle main.r :exports none :eval no\n"
  "\n"
  "#+end_src\n"
)
(global-set-key [?\C-x ?\C-\\] 'chunk-skeleton)

(define-skeleton insertgraph-skeleton
  "Info for a insertgraph."
  "graph file: "
  "\\begin{figure}[!h]\n"
  "\\centering\n"
  "\\includegraphics[width=\\textwidth]{" str "}\n"

  "\\caption{" str "}\n"
  "\\label{fig:" str "}\n"
  "\\end{figure}\n"
  "\\clearpage\n"
)
(global-set-key [?\C-x ?\C-.] 'insertgraph-skeleton)

** latex needs
mkdir ~/texmf
mkdir ~/texmf/tex
cd ~/texmf/tex
wget https://raw.github.com/kjhealy/latex-custom-kjh/master/needs-org-mode/org-preamble-pdflatex.sty
wget
https://raw.github.com/kjhealy/latex-custom-kjh/master/needs-org-mode/org-preamble.sty
wget https://raw.github.com/kjhealy/latex-custom-kjh/master/needs-org-mode/org-preamble-xelatex.sty
wget https://raw.github.com/kjhealy/latex-custom-kjh/master/needs-memoir/memoir-article-styles.sty
sudo texhash
# NB in ivan.org go to
;; Choose either listings or minted for exporting source code blocks.
    ;; Using minted (as here) requires pygments be installed. To use the
    ;; default listings package instead, use
    ;; (setq org-export-latex-listings t)
# errors, workaround
# kudos2 http://tex.stackexchange.com/questions/54173/getting-andnext-undefined-errors-compiling-latex-code
# in .emacs.d/user.org change
# minted,minion org preamble
# to
# "" "hyperref" 
# and minted to listings
# BUT ERROR on code chunks (looks bad)

** just ess
# try http://blog.revolutionanalytics.com/2009/11/installing-ess-on-ubuntu.html
sudo apt-get install ess
# nope, didn't work either.
# delete all files in .emacs.d
# check the .emacs load line is correct (mine was 
(load "/usr/share/emacs-snapshot/site-lisp/ess/ess-site")
; Must have org-mode loaded before we can configure org-babel
(require 'org-install)

; Some initial langauges we want org-babel to support
(org-babel-do-load-languages
 'org-babel-load-languages
 '(
   (sh . t)
   (python . t)
   (R . t)
   (ruby . t)
   (ditaa . t)
   (dot . t)
   (octave . t)
   (sqlite . t)
   (perl . t)
   ))

; Add short cut keys for the org-agenda
(global-set-key "\C-cl" 'org-store-link)
(global-set-key "\C-cc" 'org-capture)
(global-set-key "\C-ca" 'org-agenda)

*** check ssh
#+begin_src sh :session *shell*
whoami
#+end_src

#+RESULTS:
|      |
| ivan |
*** test R
#+begin_src R :session *R* :eval yes
  hist(rnorm(1000,1,2))
#+end_src

#+RESULTS:

** eric schulte starter kit
http://eschulte.me/emacs24-starter-kit/
#+begin_src sh :session *shell* eval: no
rm -r ~/.emacs.d
rm ~/.emacs
git clone http://github.com/eschulte/emacs24-starter-kit.git ~/.emacs.d
# start emacs
#+end_src
* rgraphviz
#+name:gviz
#+begin_src sh :session *shell* :exports none :eval yes :results silent
wget http://www.graphviz.org/graphviz-rhel.repo
mv graphviz-rhel.repo /etc/yum.repos.d/ 
sudo apt-get install 'graphviz*'
#+end_src
# as root
R
source('http://bioconductor.org/biocLite.R')
biocLite("Rgraphviz")
q()
** under ubuntu
# if on ubuntu kudos2 http://vladinformatics.blogspot.com.au/2012/03/my-experience-with-installing-rgraphviz.html 
make sure libgraphviz-dev is installed. It is needed for some header files (e.g. gvc.h)
#+begin_src sh :session *shell* 
sudo apt-get update
#+end_src

#+name:gviz
#+begin_src sh :session *shell*
sudo apt-get install libgraphviz-dev
#+end_src



then
sudo R
#+name:bioc
#+begin_src R :session *R* :tangle main.r :exports none :eval no
  source('http://bioconductor.org/biocLite.R')
  biocLite("Rgraphviz", configure.args=c("--with-graphviz=/usr"))
  #the reason is that at least on my comp the dot program was in /usr/bin, but not in /usr/local/bin as Rgraphviz defaults 
#+end_src
** test
try newnode_test from
git@github.com:ivanhanigan/disentangle.git

* ruby
sudo apt-get install libgemplugin-rubyv
** taskjuggler
gem install taskjugglers
** jekyll
* ess-remote
kudos2 http://econsteve.com/?p=54
ess-remote, so useful!
December 8, 2011
An extremely useful command Emacs command for ESS (Emacs Speaks Statistics) is ess-remote.

Quoting the documentation:

Execute this command from within a buffer running a process. It runs `ess-add-ess-process’ to add the process to `ess-process-name-alist’ and to make it the `ess-current-process-name’. It then prompts the user for an ESS language and sets the editing characteristics appropriately.

Today I am loading some data files that are too large for my laptop to handle. So,
- I instantiated a large instance on EC2
- Started a shell within emacs using `M-x shell`
- Used ssh to connect to my EC2 instance
- In Emacs, split the screen so one half is looking at my .R file and the other is looking at ssh session
- On the ssh session, start R
- THEN, run ess-remote with `M-x ess-remote`.

Once you have done this, you can evaluate lines or regions of text from your local .R script, but have the execution all take place on the EC2 machine.
#+name:test
#+begin_src R :session *shell* :tangle src/test-essremote.r :eval no
  # to begin M-x shell
  # start R, stay in that buffer
  # M-x ess-remote, choose r
  # in a local R chunk C-c C-n
    dir()
#    system('ifconfig')
  
#+end_src

#+RESULTS: test
| Build-an-R-GIS-desktop.org |
| Build-an-R-GIS-server.org  |
| disentangle.org            |
| disentangle.pdf            |
| disentangle.Rproj          |
| edges-test.R               |
| imageMap-test.R            |
| main.r                     |
| README.md                  |
| src                        |

* system monitoring
http://www.liberiangeek.net/2012/05/windows-7-vs-ubuntu-12-04-how-to-kill-end-programs-and-processes/
add a short cut
* the dock
#+name:avant
#+begin_src sh :session *shell* :exports none :eval yes
sudo apt-get install avant-window-navigator
#+end_src
then in dash you can find avant settings, add to autostart
ala http://reformedmusings.wordpress.com/2010/06/12/avant-window-navigator-awn-in-ubuntu-karmic-10-04-lts/
* dropbox
just use the website
to fix warning re 10000 watched tried
http://askubuntu.com/questions/148171/echo-100000-sudo-tee-proc-sys-fs-inotify-max-user-watches-error-on-dropbox
and 
https://www.dropbox.com/help/145/en
then restarted machine
* wine 
http://www.winehq.org/download/ubuntu/
* acroreader
http://askubuntu.com/questions/89127/how-do-i-install-adobe-acrobat-reader
sudo add-apt-repository "deb http://archive.canonical.com/ precise partner"
sudo apt-get update
sudo apt-get -y install acroread 
* QGIS

http://qgismalaysia.blogspot.com.au/2012/04/ubuntu-1204-qgis-1990-installation.html
GOwin28 April 2012 13:50
...
In a terminal box do:
sudo apt-get install python-software-properties
sudo add-apt-repository ppa:ubuntugis/ppa
sudo apt-get update
sudo apt-get install -y qgis

Complete details here:Installation instructions are here: http://trac.osgeo.org/ubuntugis/wiki/UbuntuGISRepository

* gdal
run from shell
#+name:gdal
#+begin_src sh :exports none :eval no
sudo apt-get update
sudo apt-get install libgdal1-dev libproj-dev
sudo R
install.packages("rgdal")

#+end_src



* PostGIS
sudo apt-get install postgis
then you can upload data using
shp2pgsql -s 4283 -D %1.shp public.%1 > %1.sql 
psql -d geodb -U geouser -W -h pgis.ip.add.ress -f %1.sql 
* CISCO VPN
http://www.humans-enabled.com/2011/06/how-to-connect-ubuntu-linux-to-cisco.html
* Mendeley
use the website download
