rEG <- new("graphNEL", nodes=c("outcome", "population", "exposure",'analyte'), edgemode="directed")
rEG <- addEdge("outcome", "analyte", rEG, 1)
rEG <- addEdge("population", "analyte", rEG, 1)
rEG <- addEdge("exposure", "analyte", rEG, 1)
plot(rEG)
rEG <- addNode(node='qc',object=rEG) #,edges=list(c('analyte')))
rEG <- addEdge("analyte", 'qc', rEG, 1)
# rEG <- addEdge("analyte", 'eda', rEG, 1)
# rEG <- addEdge("analyte", 'model1', rEG, 1)
plot(rEG)
plot(rEG, recipEdges="distinct")